
DROP TABLE IF EXISTS COURSES;
CREATE TABLE COURSES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COURSE_ID VARCHAR(5) NOT NULL,
    SUBJ VARCHAR(4) NOT NULL,
    TITLE TEXT,
    DESCRIPTION TEXT,
    SEMESTER VARCHAR(6) NOT NULL
);

DROP TABLE IF EXISTS CLASSES;
CREATE TABLE CLASSES (
    CRN INTEGER NOT NULL UNIQUE,
    COURSE_ID INTEGER NOT NULL,
    SECTION_ID VARCHAR(3) NOT NULL,
    SECTION_TYPE VARCHAR(3) NOT NULL,
    CR_HRS INTEGER NOT NULL,
    TUIT_CODE VARCHAR(4) NOT NULL,
    TUIT_BHRS INTEGER NOT NULL,
    DAYS VARCHAR(5),
    TIME TEXT,
    LOCATION TEXT,
    INSTRUCTOR TEXT,
    PRIMARY KEY (CRN),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);
